Add SetMetadata for FormatContext
asticode/go-astiav pull request #67
Opened 2024-08-22 09:21 UTC by Mr3h1v

#66 
support set metadata

2024-08-22 09:31 UTC, asticode requested changes
Thanks for the PR 👍 

Could you also add a simple test [here](https://github.com/asticode/go-astiav/blob/master/format_context_test.go#L51), something like:
```go
d := NewDictionnary()
d.Set("k", "v", ...)
fc3.SetMetadata(d)
require.Equal(t, "v", fc3.Metadata().Get("k")
require.Equal(t, d
```

2024-08-22 09:31 UTC, asticode commented on format_context.go
> +func (fc *FormatContext) Metadata(d *Dictionary) {
Shouldn't it be `SetMetadata` instead?

2024-08-22 09:31 UTC, asticode commented on format_context.go
> +	if d == nil {
I'd rather not ignore if `d == nil` in case someone would want to reset the metadata to `nil`

2024-08-22 11:22 UTC, asticode approved these changes

2024-08-22 11:22 UTC, merged

2024-08-22 11:22 UTC, asticode commented
Thanks again for the PR ❤️ 

Let me know whether you need me to make a tag 👍

2024-08-23 02:47 UTC, Mr3h1v commented
> Thanks again for the PR ❤️
> 
> Let me know whether you need me to make a tag 👍

I do need a tag. please make one

2024-08-23 06:55 UTC, asticode commented
I've created a `v0.18.0` tag 👍