Fix transcoding example about timebase
asticode/go-astiav pull request #69
Opened 2024-08-30 07:55 UTC by hsnks100

as-is:
The transcoding example does not work with your current testdata/video.mp4.

to-be: It should be made to work.

https://www.ffmpeg.org/doxygen/trunk/transcode_8c-example.html

in official ffmpeg example 

```
codec_ctx->pkt_timebase = stream->time_base;
...
/* In this example, we transcode to same properties (picture size,
             * sample rate etc.). These properties can be changed for output
             * streams easily using filters */
            if (dec_ctx->codec_type == AVMEDIA_TYPE_VIDEO) {
                enc_ctx->height = dec_ctx->height;
                enc_ctx->width = dec_ctx->width;
                enc_ctx->sample_aspect_ratio = dec_ctx->sample_aspect_ratio;
                /* take first format from list of supported formats */
                if (encoder->pix_fmts)
                    enc_ctx->pix_fmt = encoder->pix_fmts[0];
                else
                    enc_ctx->pix_fmt = dec_ctx->pix_fmt;
                /* video time_base can be set to whatever is handy and supported by encoder */
                enc_ctx->time_base = av_inv_q(dec_ctx->framerate); // HERE
            } else {
                enc_ctx->sample_rate = dec_ctx->sample_rate;
                ret = av_channel_layout_copy(&enc_ctx->ch_layout, &dec_ctx->ch_layout);
                if (ret < 0)
                    return ret;
                /* take first format from list of supported formats */
                enc_ctx->sample_fmt = encoder->sample_fmts[0];
                enc_ctx->time_base = (AVRational){1, enc_ctx->sample_rate}; // HERE
            }
```

I modified your example by referencing the C example.

2024-08-30 13:57 UTC, asticode requested changes
Thanks for the PR

2024-08-30 16:37 UTC, hsnks100 commented on examples/transcoding/main.go
> +				"time_base":    s.decCodecContext.Framerate().Inv().String(),
applied your comment, and it works.

2024-08-31 12:14 UTC, asticode requested changes

2024-08-31 12:14 UTC, asticode commented on examples/transcoding/main.go
> +				//"time_base":    s.decCodecContext.Framerate().Invert().String(),
Could you remove this comment?

2024-08-31 13:00 UTC, merged

2024-08-31 13:00 UTC, asticode commented
Thanks for the PR ❤️